export const districts = [
    { code: "C&W", name: "Central and Western" },
    { code: "WC", name: "Wan Chai" },
    { code: "E", name: "Eastern" },
    { code: "S", name: "Southern" },
    { code: "YTM", name: "Yau Tsim Mong" },
    { code: "SSP", name: "Sham Shui Po" },
    { code: "KC", name: "Kowloon City" },
    { code: "WTS", name: "Wong Tai Sin" },
    { code: "KT", name: "Kwun Tong" },
    { code: "K&T", name: "Kwai Tsing" },
    { code: "TW", name: "Tsuen Wan" },
    { code: "TM", name: "Tuen Mun" },
    { code: "YL", name: "Yuen Long" },
    { code: "N", name: "North" },
    { code: "TP", name: "Tai Po" },
    { code: "ST", name: "Sha Tin" },
    { code: "SK", name: "Sai Kung" },
    { code: "Is", name: "Islands" },
]